### ISSUE TITLE
print() is a function in Python 3

### ISSUE THREAD

**Issue by cclauss** [huseinzol05/Gather-Deployment#1]
[flake8](http://flake8.pycqa.org) testing of https://github.com/huseinzol05/Gather-Tensorflow-Serving on Python 3.7.1

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./4.classification-flask-gunicorn/two-graph/model_nn.py:11:76: F821 undefined name 'xrange'
        self.rnn_cells = tf.nn.rnn_cell.MultiRNNCell([lstm_cell() for _ in xrange(num_layers)])
                                                                           ^
./4.classification-flask-gunicorn/two-graph/train.py:17:36: E999 SyntaxError: invalid syntax
    print "done load embedded files"
                                   ^
./4.classification-flask-gunicorn/two-graph/word2vec.py:110:23: E999 SyntaxError: invalid syntax
    print "Data size: " + str(len(words_real))
                      ^
./4.classification-flask-gunicorn/two-graph/server.py:58:46: E999 SyntaxError: invalid syntax
    print "done load sentiment embedded files"
                                             ^
3     E999 SyntaxError: invalid syntax
1     F821 undefined name 'xrange'
4
```

__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. Most other flake8 issues are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

**Comment by huseinzol05** [comment]
Oh, I am sorry for that folder, that one is not necessary anymore. Removed, thanks!
