### ISSUE TITLE
Livestream not showing any object detection

### ISSUE THREAD

**Issue by asyrafzlkln96** [huseinzol05/Gather-Deployment#3]
Hi, I have run the app.py from flasksocketio-object-detection folder.
The livestream dashboard just show black screen, no object detection, but my camera from laptop 
has open. Can you help me?

**Comment by huseinzol05** [comment]
Paste some logs here.

**Comment by asyrafzlkln96** [comment]
127.0.0.1 - - [03/Nov/2019 19:18:33] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [03/Nov/2019 19:18:33] "GET /static/css/materialize.min.css HTTP/1.1" 200 -
127.0.0.1 - - [03/Nov/2019 19:18:33] "GET /static/css/style.css HTTP/1.1" 200 -
127.0.0.1 - - [03/Nov/2019 19:18:33] "GET /static/js/jquery-2.1.1.min.js HTTP/1.1" 200 -
127.0.0.1 - - [03/Nov/2019 19:18:33] "GET /static/js/materialize.min.js HTTP/1.1" 200 -
127.0.0.1 - - [03/Nov/2019 19:18:33] "GET /static/js/socket.io.slim.js HTTP/1.1" 200 -
127.0.0.1 - - [03/Nov/2019 19:18:33] "GET /static/js/script.js HTTP/1.1" 200 -
127.0.0.1 - - [03/Nov/2019 19:18:35] "GET /video_feed HTTP/1.1" 200 -
127.0.0.1 - - [03/Nov/2019 19:18:35] "GET /static/fonts/roboto/Roboto-Regular.woff2 HTTP/1.1" 200 -
127.0.0.1 - - [03/Nov/2019 19:24:47] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [03/Nov/2019 19:24:48] "GET /video_feed HTTP/1.1" 200 -
127.0.0.1 - - [03/Nov/2019 19:55:52] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [03/Nov/2019 19:55:52] "GET /static/css/materialize.min.css HTTP/1.1" 200 -
127.0.0.1 - - [03/Nov/2019 19:55:52] "GET /static/css/style.css HTTP/1.1" 200 -
127.0.0.1 - - [03/Nov/2019 19:55:52] "GET /video_feed HTTP/1.1" 200 -
127.0.0.1 - - [03/Nov/2019 19:55:52] "GET /static/js/jquery-2.1.1.min.js HTTP/1.1" 200 -
127.0.0.1 - - [03/Nov/2019 19:55:52] "GET /static/js/materialize.min.js HTTP/1.1" 200 -
127.0.0.1 - - [03/Nov/2019 19:55:52] "GET /static/js/script.js HTTP/1.1" 200 -
127.0.0.1 - - [03/Nov/2019 19:55:52] "GET /static/js/socket.io.slim.js HTTP/1.1" 200 -
127.0.0.1 - - [03/Nov/2019 20:06:05] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [03/Nov/2019 20:06:05] "GET /video_feed HTTP/1.1" 200 -
127.0.0.1 - - [03/Nov/2019 20:06:06] "GET /socket.io/?EIO=3&transport=polling&t=Muqbs5a HTTP/1.1" 200 -
127.0.0.1 - - [03/Nov/2019 20:11:20] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [03/Nov/2019 20:11:20] "GET /video_feed HTTP/1.1" 200 -


Then the tab just crashed.

**Comment by huseinzol05** [comment]
I guess you got performance issue. the cpu took a very long time just to
compute on 1 frame. Tried with GPU?
